python preprocess.py -i ./datasetv2/images/regions_dataset+Middlewest+5/RGB/400 -o ./datasetv2/new/regions_dataset+Middlewest+5/RGB/400 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+Middlewest+5/RGB/512 -o ./datasetv2/new/regions_dataset+Middlewest+5/RGB/512 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+Middlewest+5/RGB/256 -o ./datasetv2/new/regions_dataset+Middlewest+5/RGB/256 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+Middlewest+5/GRAYSCALE/400 -o ./datasetv2/new/regions_dataset+Middlewest+5/GRAYSCALE/400 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+Middlewest+5/GRAYSCALE/512 -o ./datasetv2/new/regions_dataset+Middlewest+5/GRAYSCALE/512 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+Middlewest+5/GRAYSCALE/256 -o ./datasetv2/new/regions_dataset+Middlewest+5/GRAYSCALE/256 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+Middlewest+20/RGB/400 -o ./datasetv2/new/regions_dataset+Middlewest+20/RGB/400 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+Middlewest+20/RGB/512 -o ./datasetv2/new/regions_dataset+Middlewest+20/RGB/512 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+Middlewest+20/RGB/256 -o ./datasetv2/new/regions_dataset+Middlewest+20/RGB/256 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+Middlewest+20/GRAYSCALE/400 -o ./datasetv2/new/regions_dataset+Middlewest+20/GRAYSCALE/400 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+Middlewest+20/GRAYSCALE/512 -o ./datasetv2/new/regions_dataset+Middlewest+20/GRAYSCALE/512 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+Middlewest+20/GRAYSCALE/256 -o ./datasetv2/new/regions_dataset+Middlewest+20/GRAYSCALE/256 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+South+10/RGB/400 -o ./datasetv2/new/regions_dataset+South+10/RGB/400 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+South+10/RGB/512 -o ./datasetv2/new/regions_dataset+South+10/RGB/512 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+South+10/RGB/256 -o ./datasetv2/new/regions_dataset+South+10/RGB/256 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+South+10/GRAYSCALE/400 -o ./datasetv2/new/regions_dataset+South+10/GRAYSCALE/400 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+South+10/GRAYSCALE/512 -o ./datasetv2/new/regions_dataset+South+10/GRAYSCALE/512 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+South+10/GRAYSCALE/256 -o ./datasetv2/new/regions_dataset+South+10/GRAYSCALE/256 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+North+5/RGB/400 -o ./datasetv2/new/regions_dataset+North+5/RGB/400 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+North+5/RGB/512 -o ./datasetv2/new/regions_dataset+North+5/RGB/512 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+North+5/RGB/256 -o ./datasetv2/new/regions_dataset+North+5/RGB/256 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+North+5/GRAYSCALE/400 -o ./datasetv2/new/regions_dataset+North+5/GRAYSCALE/400 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+North+5/GRAYSCALE/512 -o ./datasetv2/new/regions_dataset+North+5/GRAYSCALE/512 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+North+5/GRAYSCALE/256 -o ./datasetv2/new/regions_dataset+North+5/GRAYSCALE/256 -z 3
python preprocess.py -i ./datasetv2/images/pr_dataset+10/RGB/400 -o ./datasetv2/new/pr_dataset+10/RGB/400 -z 3
python preprocess.py -i ./datasetv2/images/pr_dataset+10/RGB/512 -o ./datasetv2/new/pr_dataset+10/RGB/512 -z 3
python preprocess.py -i ./datasetv2/images/pr_dataset+10/RGB/256 -o ./datasetv2/new/pr_dataset+10/RGB/256 -z 3
python preprocess.py -i ./datasetv2/images/pr_dataset+10/GRAYSCALE/400 -o ./datasetv2/new/pr_dataset+10/GRAYSCALE/400 -z 3
python preprocess.py -i ./datasetv2/images/pr_dataset+10/GRAYSCALE/512 -o ./datasetv2/new/pr_dataset+10/GRAYSCALE/512 -z 3
python preprocess.py -i ./datasetv2/images/pr_dataset+10/GRAYSCALE/256 -o ./datasetv2/new/pr_dataset+10/GRAYSCALE/256 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+North+20/RGB/400 -o ./datasetv2/new/regions_dataset+North+20/RGB/400 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+North+20/RGB/512 -o ./datasetv2/new/regions_dataset+North+20/RGB/512 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+North+20/RGB/256 -o ./datasetv2/new/regions_dataset+North+20/RGB/256 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+North+20/GRAYSCALE/400 -o ./datasetv2/new/regions_dataset+North+20/GRAYSCALE/400 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+North+20/GRAYSCALE/512 -o ./datasetv2/new/regions_dataset+North+20/GRAYSCALE/512 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+North+20/GRAYSCALE/256 -o ./datasetv2/new/regions_dataset+North+20/GRAYSCALE/256 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+Southeast+10/RGB/400 -o ./datasetv2/new/regions_dataset+Southeast+10/RGB/400 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+Southeast+10/RGB/512 -o ./datasetv2/new/regions_dataset+Southeast+10/RGB/512 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+Southeast+10/RGB/256 -o ./datasetv2/new/regions_dataset+Southeast+10/RGB/256 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+Southeast+10/GRAYSCALE/400 -o ./datasetv2/new/regions_dataset+Southeast+10/GRAYSCALE/400 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+Southeast+10/GRAYSCALE/512 -o ./datasetv2/new/regions_dataset+Southeast+10/GRAYSCALE/512 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+Southeast+10/GRAYSCALE/256 -o ./datasetv2/new/regions_dataset+Southeast+10/GRAYSCALE/256 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+Middlewest+10/RGB/400 -o ./datasetv2/new/regions_dataset+Middlewest+10/RGB/400 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+Middlewest+10/RGB/512 -o ./datasetv2/new/regions_dataset+Middlewest+10/RGB/512 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+Middlewest+10/RGB/256 -o ./datasetv2/new/regions_dataset+Middlewest+10/RGB/256 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+Middlewest+10/GRAYSCALE/400 -o ./datasetv2/new/regions_dataset+Middlewest+10/GRAYSCALE/400 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+Middlewest+10/GRAYSCALE/512 -o ./datasetv2/new/regions_dataset+Middlewest+10/GRAYSCALE/512 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+Middlewest+10/GRAYSCALE/256 -o ./datasetv2/new/regions_dataset+Middlewest+10/GRAYSCALE/256 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+South+20/RGB/400 -o ./datasetv2/new/regions_dataset+South+20/RGB/400 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+South+20/RGB/512 -o ./datasetv2/new/regions_dataset+South+20/RGB/512 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+South+20/RGB/256 -o ./datasetv2/new/regions_dataset+South+20/RGB/256 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+South+20/GRAYSCALE/400 -o ./datasetv2/new/regions_dataset+South+20/GRAYSCALE/400 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+South+20/GRAYSCALE/512 -o ./datasetv2/new/regions_dataset+South+20/GRAYSCALE/512 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+South+20/GRAYSCALE/256 -o ./datasetv2/new/regions_dataset+South+20/GRAYSCALE/256 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+North+10/RGB/400 -o ./datasetv2/new/regions_dataset+North+10/RGB/400 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+North+10/RGB/512 -o ./datasetv2/new/regions_dataset+North+10/RGB/512 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+North+10/RGB/256 -o ./datasetv2/new/regions_dataset+North+10/RGB/256 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+North+10/GRAYSCALE/400 -o ./datasetv2/new/regions_dataset+North+10/GRAYSCALE/400 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+North+10/GRAYSCALE/512 -o ./datasetv2/new/regions_dataset+North+10/GRAYSCALE/512 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+North+10/GRAYSCALE/256 -o ./datasetv2/new/regions_dataset+North+10/GRAYSCALE/256 -z 3
python preprocess.py -i ./datasetv2/images/br_dataset+5/RGB/400 -o ./datasetv2/new/br_dataset+5/RGB/400 -z 3
python preprocess.py -i ./datasetv2/images/br_dataset+5/RGB/512 -o ./datasetv2/new/br_dataset+5/RGB/512 -z 3
python preprocess.py -i ./datasetv2/images/br_dataset+5/RGB/256 -o ./datasetv2/new/br_dataset+5/RGB/256 -z 3
python preprocess.py -i ./datasetv2/images/br_dataset+5/GRAYSCALE/400 -o ./datasetv2/new/br_dataset+5/GRAYSCALE/400 -z 3
python preprocess.py -i ./datasetv2/images/br_dataset+5/GRAYSCALE/512 -o ./datasetv2/new/br_dataset+5/GRAYSCALE/512 -z 3
python preprocess.py -i ./datasetv2/images/br_dataset+5/GRAYSCALE/256 -o ./datasetv2/new/br_dataset+5/GRAYSCALE/256 -z 3
python preprocess.py -i ./datasetv2/images/br_dataset+10/RGB/400 -o ./datasetv2/new/br_dataset+10/RGB/400 -z 3
python preprocess.py -i ./datasetv2/images/br_dataset+10/RGB/512 -o ./datasetv2/new/br_dataset+10/RGB/512 -z 3
python preprocess.py -i ./datasetv2/images/br_dataset+10/RGB/256 -o ./datasetv2/new/br_dataset+10/RGB/256 -z 3
python preprocess.py -i ./datasetv2/images/br_dataset+10/GRAYSCALE/400 -o ./datasetv2/new/br_dataset+10/GRAYSCALE/400 -z 3
python preprocess.py -i ./datasetv2/images/br_dataset+10/GRAYSCALE/512 -o ./datasetv2/new/br_dataset+10/GRAYSCALE/512 -z 3
python preprocess.py -i ./datasetv2/images/br_dataset+10/GRAYSCALE/256 -o ./datasetv2/new/br_dataset+10/GRAYSCALE/256 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+Southeast+20/RGB/400 -o ./datasetv2/new/regions_dataset+Southeast+20/RGB/400 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+Southeast+20/RGB/512 -o ./datasetv2/new/regions_dataset+Southeast+20/RGB/512 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+Southeast+20/RGB/256 -o ./datasetv2/new/regions_dataset+Southeast+20/RGB/256 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+Southeast+20/GRAYSCALE/400 -o ./datasetv2/new/regions_dataset+Southeast+20/GRAYSCALE/400 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+Southeast+20/GRAYSCALE/512 -o ./datasetv2/new/regions_dataset+Southeast+20/GRAYSCALE/512 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+Southeast+20/GRAYSCALE/256 -o ./datasetv2/new/regions_dataset+Southeast+20/GRAYSCALE/256 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+Northeast+10/RGB/400 -o ./datasetv2/new/regions_dataset+Northeast+10/RGB/400 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+Northeast+10/RGB/512 -o ./datasetv2/new/regions_dataset+Northeast+10/RGB/512 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+Northeast+10/RGB/256 -o ./datasetv2/new/regions_dataset+Northeast+10/RGB/256 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+Northeast+10/GRAYSCALE/400 -o ./datasetv2/new/regions_dataset+Northeast+10/GRAYSCALE/400 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+Northeast+10/GRAYSCALE/512 -o ./datasetv2/new/regions_dataset+Northeast+10/GRAYSCALE/512 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+Northeast+10/GRAYSCALE/256 -o ./datasetv2/new/regions_dataset+Northeast+10/GRAYSCALE/256 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+South+5/RGB/400 -o ./datasetv2/new/regions_dataset+South+5/RGB/400 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+South+5/RGB/512 -o ./datasetv2/new/regions_dataset+South+5/RGB/512 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+South+5/RGB/256 -o ./datasetv2/new/regions_dataset+South+5/RGB/256 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+South+5/GRAYSCALE/400 -o ./datasetv2/new/regions_dataset+South+5/GRAYSCALE/400 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+South+5/GRAYSCALE/512 -o ./datasetv2/new/regions_dataset+South+5/GRAYSCALE/512 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+South+5/GRAYSCALE/256 -o ./datasetv2/new/regions_dataset+South+5/GRAYSCALE/256 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+Northeast+5/RGB/400 -o ./datasetv2/new/regions_dataset+Northeast+5/RGB/400 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+Northeast+5/RGB/512 -o ./datasetv2/new/regions_dataset+Northeast+5/RGB/512 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+Northeast+5/RGB/256 -o ./datasetv2/new/regions_dataset+Northeast+5/RGB/256 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+Northeast+5/GRAYSCALE/400 -o ./datasetv2/new/regions_dataset+Northeast+5/GRAYSCALE/400 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+Northeast+5/GRAYSCALE/512 -o ./datasetv2/new/regions_dataset+Northeast+5/GRAYSCALE/512 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+Northeast+5/GRAYSCALE/256 -o ./datasetv2/new/regions_dataset+Northeast+5/GRAYSCALE/256 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+Southeast+5/RGB/400 -o ./datasetv2/new/regions_dataset+Southeast+5/RGB/400 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+Southeast+5/RGB/512 -o ./datasetv2/new/regions_dataset+Southeast+5/RGB/512 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+Southeast+5/RGB/256 -o ./datasetv2/new/regions_dataset+Southeast+5/RGB/256 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+Southeast+5/GRAYSCALE/400 -o ./datasetv2/new/regions_dataset+Southeast+5/GRAYSCALE/400 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+Southeast+5/GRAYSCALE/512 -o ./datasetv2/new/regions_dataset+Southeast+5/GRAYSCALE/512 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+Southeast+5/GRAYSCALE/256 -o ./datasetv2/new/regions_dataset+Southeast+5/GRAYSCALE/256 -z 3
python preprocess.py -i ./datasetv2/images/pr_dataset+20/RGB/400 -o ./datasetv2/new/pr_dataset+20/RGB/400 -z 3
python preprocess.py -i ./datasetv2/images/pr_dataset+20/RGB/512 -o ./datasetv2/new/pr_dataset+20/RGB/512 -z 3
python preprocess.py -i ./datasetv2/images/pr_dataset+20/RGB/256 -o ./datasetv2/new/pr_dataset+20/RGB/256 -z 3
python preprocess.py -i ./datasetv2/images/pr_dataset+20/GRAYSCALE/400 -o ./datasetv2/new/pr_dataset+20/GRAYSCALE/400 -z 3
python preprocess.py -i ./datasetv2/images/pr_dataset+20/GRAYSCALE/512 -o ./datasetv2/new/pr_dataset+20/GRAYSCALE/512 -z 3
python preprocess.py -i ./datasetv2/images/pr_dataset+20/GRAYSCALE/256 -o ./datasetv2/new/pr_dataset+20/GRAYSCALE/256 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+Northeast+20/RGB/400 -o ./datasetv2/new/regions_dataset+Northeast+20/RGB/400 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+Northeast+20/RGB/512 -o ./datasetv2/new/regions_dataset+Northeast+20/RGB/512 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+Northeast+20/RGB/256 -o ./datasetv2/new/regions_dataset+Northeast+20/RGB/256 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+Northeast+20/GRAYSCALE/400 -o ./datasetv2/new/regions_dataset+Northeast+20/GRAYSCALE/400 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+Northeast+20/GRAYSCALE/512 -o ./datasetv2/new/regions_dataset+Northeast+20/GRAYSCALE/512 -z 3
python preprocess.py -i ./datasetv2/images/regions_dataset+Northeast+20/GRAYSCALE/256 -o ./datasetv2/new/regions_dataset+Northeast+20/GRAYSCALE/256 -z 3
python preprocess.py -i ./datasetv2/images/br_dataset+20/RGB/400 -o ./datasetv2/new/br_dataset+20/RGB/400 -z 3
python preprocess.py -i ./datasetv2/images/br_dataset+20/RGB/512 -o ./datasetv2/new/br_dataset+20/RGB/512 -z 3
python preprocess.py -i ./datasetv2/images/br_dataset+20/RGB/256 -o ./datasetv2/new/br_dataset+20/RGB/256 -z 3
python preprocess.py -i ./datasetv2/images/br_dataset+20/GRAYSCALE/400 -o ./datasetv2/new/br_dataset+20/GRAYSCALE/400 -z 3
python preprocess.py -i ./datasetv2/images/br_dataset+20/GRAYSCALE/512 -o ./datasetv2/new/br_dataset+20/GRAYSCALE/512 -z 3
python preprocess.py -i ./datasetv2/images/br_dataset+20/GRAYSCALE/256 -o ./datasetv2/new/br_dataset+20/GRAYSCALE/256 -z 3
python preprocess.py -i ./datasetv2/images/pr_dataset+5/RGB/400 -o ./datasetv2/new/pr_dataset+5/RGB/400 -z 3
python preprocess.py -i ./datasetv2/images/pr_dataset+5/RGB/512 -o ./datasetv2/new/pr_dataset+5/RGB/512 -z 3
python preprocess.py -i ./datasetv2/images/pr_dataset+5/RGB/256 -o ./datasetv2/new/pr_dataset+5/RGB/256 -z 3
python preprocess.py -i ./datasetv2/images/pr_dataset+5/GRAYSCALE/400 -o ./datasetv2/new/pr_dataset+5/GRAYSCALE/400 -z 3
python preprocess.py -i ./datasetv2/images/pr_dataset+5/GRAYSCALE/512 -o ./datasetv2/new/pr_dataset+5/GRAYSCALE/512 -z 3
python preprocess.py -i ./datasetv2/images/pr_dataset+5/GRAYSCALE/256 -o ./datasetv2/new/pr_dataset+5/GRAYSCALE/256 -z 3
